### PR TITLE
Fix #17 Force all-the-way-through solutions where there is an announc…

### LINKED ISSUE #17: Force all-the-way-through solutions where there is an announced mate
When working only with mates, a lot of times the proposed solution doesn't cover the whole mate sequence. It would be nice to force the puzzler to annotate the whole solution when there is an announced mate.

An example:

[Crazyhouse] - In this case, only B@f8 is printed, while the desired solution would be (shortest forced mate): B@f8+, Ke6, exf5+, Kxf5, Ng3+, Ke6, B@d5+, Ke5, d4#
`3r4/p1p1kpQp/3p1N1p/5bbN/4P3/3PP3/PPq2nPP/r3BK1R[Brnppp] w - - 4 39;variant crazyhouse;bm B@f8;eval #5;difficulty 6;quality 1.00;type mate;pv B@f8`

### PR DESCRIPTION
**Pull request by gbtami**
…ed mate

### CODE REVIEW

**Comment by ianfab** [comment]
The current behavior from my perspective is intentional, avoiding ambiguous solutions. Simply allowing ambiguous solutions without having a way to distinguish clean and ambiguous puzzles or specifying alternative solutions IMO is problematic and a use case specific behavior. Depending on whether/how a consuming application can handle ambiguous solutions, I would rather
* Allow to filter out incomplete mate puzzles by distinguishing them in the `type`. This could e.g. easily be detected by comparing the pv length (minus optional initial move) with the mate distance that is written to `eval`. Or of course one could check if the end position is final.
* Optionally allow ambiguous solutions by making the relative mate distance ratio/threshold configurable in https://github.com/ianfab/chess-variant-puzzler/blob/6dacc5a068074135a50be66f7d8f756decd1d232/puzzler.py#L57-L58 or make it configurable to only apply this condition at the root.

**Comment by ianfab** [comment]
Let me illustrate why stopping problems at points of ambiguity isn't just about the problem of resolving ambiguity itself, but also about making it a good puzzle. E.g., let's take a simple KRKR position where you can win the rook https://lichess.org/analysis/8/8/8/8/8/r3k3/8/4K2R_w_-_-_0_1. The puzzle here is to spot the skewer. Completing it to a mate puzzle with a long KRK mate sequence destroys the puzzle. That is why even when allowing ambiguity, there needs to be a sound definition of which level of ambiguity is acceptable.

Since the puzzle identification algorithm intentionally is kept simple in order to also learn something about what constitutes a good puzzle, I would prefer to avoid hard-coded rules like accepting mate completions of length <= X that are arbitrary. If implementing it at all, I would rather go into the direction of measuring the level of ambiguity, e.g., the number of branching points and the mate distance difference, and take the decision where to stop the puzzle based on optimizing the trade-off between information gain and ambiguity.

**Comment by gbtami** [comment]
I have the feeling that you misunderstand the intention of my PR, possible because my code is not correct :) It absolutely doesn't want to change the puzzle creation algorithm in any way.
The only one thing it wants to changes is to complete the partial PV in already created(!) mate in X puzzles with first possible mate in X move sequence if there was any in engine analysis output.

**Comment by ianfab** [comment]
Yes, I know, and my above two comments are talking exactly about that. Of course the change does not **create** new puzzles, but **extends** the solution which can (and will) make it ambiguous.

What this in effect does is to circumvent the truncation of the PV that another part of the code **intentionally** does. Instead of letting different parts of the code fight against each other I would prefer to tweak the existing code to achieve the desired behavior. Please remember that the puzzle identification is applied recursively on each move of the PV and that the first position in the PV that does not constitute a puzzle is the point where the PV is truncated. So a truncated PV rarely means that the algorithm did not see far enough (though that can happen at low depth), but that it decided that the puzzle would deteriorate by extending the PV. So if you disagree with that, you need to define in which case extending the PV still adds value, which is what I tried to outline in the above two comments.

**Comment by gbtami** [comment]
OK, I think I understand the problem now. Thx for being patient and explaining it several times with different words.

**Pull request closed without merging**
